# Generated by Django 4.2 on 2026-02-15 05:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('card_type', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('number', models.CharField(max_length=32)),
                ('expiry_date', models.DateField()),
                ('partner_reference', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Bankcard',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('order_number', models.CharField(max_length=128)),
                ('currency', models.CharField(default='EUR', max_length=12)),
                ('amount_allocated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_debited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('code', models.SlugField(max_length=128, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(blank=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(blank=True, max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payment.source')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='source',
            name='source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='payment.sourcetype'),
        ),
    ]
