events {
    worker_connections 1024;
}

http {
    upstream django_monolith {
        server host.docker.internal:8000;
    }
    upstream offers_microservice {
        server host.docker.internal:8001;
    }
    upstream basket_microservice {
        server host.docker.internal:8002;
    }
    upstream catalogue_microservice {
        server host.docker.internal:8003;
    }

    server {
        listen 80;

        location /health {
            return 200 "Gateway OK\n";
            add_header Content-Type text/plain;
        }

        location /strangler-status {
            return 200 '{
                "phase": "2 - Nach Catalogue Migration",
                "migriert": {
                    "offers":    "Microservice 8001",
                    "basket":    "Microservice 8002",
                    "catalogue": "Microservice 8003"
                },
                "nicht_migriert": {
                    "orders":  "Monolith 8000",
                    "payment": "Monolith 8000"
                },
                "bridge": "gelöscht!"
            }';
            add_header Content-Type application/json;
        }

        # ALLE MIGRIERTEN SERVICES
        location /api/offers {
            set $backend_used "offers_microservice";
            proxy_pass http://offers_microservice;
            proxy_set_header Host $host;
            add_header X-Backend-Used $backend_used always;
        }

        location /api/basket {
            set $backend_used "basket_microservice";
            proxy_pass http://basket_microservice;
            proxy_set_header Host $host;
            add_header X-Backend-Used $backend_used always;
        }

        location /api/catalogue {
            set $backend_used "catalogue_microservice";
            proxy_pass http://catalogue_microservice;
            proxy_set_header Host $host;
            add_header X-Backend-Used $backend_used always;
        }

        #NOCH NICHT MIGRIERT
        location /api/orders {
            set $backend_used "monolith_orders";
            proxy_pass http://django_monolith;
            proxy_set_header Host $host;
            add_header X-Backend-Used $backend_used always;
        }


        location / {
            proxy_pass http://django_monolith;
            proxy_set_header Host $host;
        }
    }
}